In [1]:
import torch

In [47]:
import math
import numpy as np

In [210]:
x1 = torch.tensor(1.0, requires_grad=True)
x2 = torch.tensor(math.pi/3, requires_grad=True)
w1 = torch.tensor(3.0, requires_grad=True)
w2 = torch.tensor(1.0, requires_grad=True)

In [211]:
sin_xw= torch.sin(x1*w1)
cos_xw = torch.cos(x2*w2)
sin_xw_2=sin_xw**2
sum_sin_cos = sin_xw_2 + cos_xw
sum1_sin_cos = sum_sin_cos+2
f_xw = 1/ sum1_sin_cos

In [212]:
f_xw.backward()

In [270]:
print("gradient of x1:",round(x1.grad.item(),4))
print("gradient of x2:",round(x2.grad.item(),4))
print("gradient of w1:",round(w1.grad.item(),4))
print("gradient of w2:",round(w2.grad.item(),4))

gradient of x1: 0.132
gradient of x2: 0.1364
gradient of w1: 0.044
gradient of w2: 0.1428


In [242]:
f_xw

tensor(0.3968, grad_fn=<MulBackward0>)

In [259]:
np.cos(3)*-0.0444

0.04395566684905978

In [258]:
0.1411 *2 * 0.1575

0.0444465

In [240]:
-np.sin(-6.3512)

0.06796226563781194

### Problem 2 (Practice of vector‐based backpropagation). 

In [497]:
W=torch.tensor([[.5,1.0,-1.0],[3.0,1.0,.5],[-1.0,-1.0,-2.0]],requires_grad = True)
X = torch.tensor([[10.0],[10.0],[-10.0]],requires_grad=True)

In [498]:
WX=torch.mm(W,X)
sigmoid_WX = torch.sigmoid(WX)
norm_WX = torch.norm(sigmoid_WX)**2
WX.retain_grad()
sigmoid_WX.retain_grad()
norm_WX.retain_grad()
print(norm_WX)

tensor(2.2500, grad_fn=<PowBackward0>)


In [499]:
norm_WX.backward()

In [500]:
print(W.grad)
print(X.grad)

tensor([[ 0.0000,  0.0000, -0.0000],
        [ 0.0000,  0.0000, -0.0000],
        [ 2.5000,  2.5000, -2.5000]])
tensor([[-0.2500],
        [-0.2500],
        [-0.5000]])


In [501]:
sigmoid_WX.grad

tensor([[2.],
        [2.],
        [1.]])

In [502]:
WX.grad

tensor([[0.0000],
        [0.0000],
        [0.2500]])

In [456]:
a=torch.tensor([[0.1,0.5],[-0.3,.8]],requires_grad=True)
b=torch.tensor([[.2],[.4]],requires_grad=True)

In [457]:
c=torch.norm(a@b)

In [458]:
c.backward()

In [459]:
a.grad

tensor([[0.1292, 0.2584],
        [0.1527, 0.3054]])

In [460]:
b.grad

tensor([[-0.1644],
        [ 0.9337]])

In [462]:
torch.norm(a@b)

tensor(0.3406, grad_fn=<NormBackward0>)

In [465]:
np.linalg.norm([[0.22],[0.26]],axis=0)

array([0.34058773])

In [466]:
0.22*0.22 + 0.26*0.26

0.116